version: "3.9"

services:
    salt-server:
        build: ../../../salt-server/
        restart: unless-stopped
        network_mode: host
        environment:
            - PORT=${SERVER_PORT}
            - NODE_ENV=production
            - CORS_ALLOWED_ORIGINS=*
            - PORT=${PORT}
            - DB_CLIENT=${DB_CLIENT}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
