version: "3.9"

services:
    salt-frontend:
        build: ../../../salt-frontend/
        restart: unless-stopped
        ports:
            - "${PORT}:8080"
        environment:
            - LOCALE=pt-BR
            - FALLBACK_LOCALE=pt-BR
            - APP_API=${SERVER_URL}
