version: "3.9"

services:
    cms-frontend:
        build:
            context: ../../../salt-frontend/
            args:
                - LOCALE=pt-BR
                - FALLBACK_LOCALE=pt-BR
                - APP_API=${SERVER_URL}
        restart: unless-stopped
        ports:
            - "${PORT}:8080"
        environment:
            - PORT=8080